version: '3'

env:
  # Unset VIRTUAL_ENV to avoid uv warnings when the shell has a stale environment activated
  VIRTUAL_ENV: ''

tasks:
  install:
    desc: Install dependencies
    cmds:
      - uv sync

  run:
    desc: Run the application
    cmds:
      - uv run subsync

  test:
    desc: Run tests
    cmds:
      - uv run pytest

  lint:
    desc: Lint the code
    cmds:
      - uv run ruff check .

  format:
    desc: Format the code
    cmds:
      - uv run ruff format .
